example/simple-login/package.json, package.json, src/profile_service/index.js, test/payload-other-party-empty-object.json, test/payload-other-party-non-existent.json, test/payload-other-party-null.json, test/yoti-client.spec.js
update to allow empty profiles, also updated package.json to add dependencies  to package.json
=> DA-847 updated the sdk to allow empty profile sharing.

package-lock.json, package.json
I ran 'npm install' and the spacing changed, so i've committed this. Also add repo field, which was showing an error when this command was run. 
Additionally, a package-lock.json file was created - [we've committed this to the example project previously](https://github.com/getyoti/yoti-node-sdk/pull/9#issuecomment-336067690), would you agree that it would be best to commit this too?
=> [SDK-129]: Updates to package.json after MIT license change

README.md, examples/profile/index.js, examples/profile/views/pages/index.ejs, examples/profile/views/pages/profile.ejs, package-lock.json, src/profile_service/index.js, src/yoti_common/age.js
I will add a test case for this after this review if needed.
=> SDK-280 : Add age verified helper

package-lock.json, package.json
- Update packages for patch release `v3.2.1` (unpinning)
- We can merge into branch `v3.2.x` and tag from there
>Note: Changes in 8f0f06f47f7d5bd051df3f76c48f41dd74c326a3 include a major update for `base64-url` so we cannot release it as a patch release
=> SDK-785: Update packages

examples/profile/views/pages/index.ejs
- Updated to `browser.2.2.0.js`
=> SDK-635: Update browser.js

package-lock.json
=> SDK-802: Update packages

CONTRIBUTING.md, package-lock.json, package.json, src/client/index.js, src/yoti_common/index.js, tests/client.spec.js
- Replaced URSA with [Node-RSA](https://www.npmjs.com/package/node-rsa)
Example project and unit tests pass in:
- 8.9.4
- 9.11.2
- 10.15.1
- 11.10.0
=> SDK-501: Replace URSA

examples/aml-check/package-lock.json, examples/aml-check/package.json, examples/profile/package-lock.json, examples/profile/package.json
=> SDK-808: Update examples to use v3.3.0

examples/aml-check/package-lock.json, examples/aml-check/package.json, examples/profile/package-lock.json, examples/profile/package.json
=> SDK-808: Merge development -> master

examples/profile/views/pages/profile.ejs, tests/profile-service.profile.spec.js, tests/sample-data/profile-service/profile.json
- Added test coverage
- Added to example project
=> SDK-831: Structured postal address

src/yoti_common/attribute.converter.js, tests/yoti-common.attribute.converter.spec.js
- Handling INT values int `AttributeConverter::convertValueBasedOnContentType()`
=> SDK-870: Support INT values

.gitignore, .travis.yml, examples/aml-check/package.json, examples/profile/package.json, package-lock.json, package.json
- Running `npm ci`
- Reinstated lock file
- Continuing to check compatibility with latest dependencies in Node 6, 8, 9, 10 and 11
- Added linting and unit tests to pre-commit hook (adding to implementation in #30)
=> SDK-915: Run npm ci

README.md, src/profile_service/activity.details.js, tests/profile-service.spec.js
=> SDK-923: Add getter for receipt ID

README.md
- Added missing require to _README_ example
=> SDK-439: Add missing require to README example

examples/aml-check/aml-usa.js
=> SDK-918: Correct zip code

package-lock.json
=> Release 3.5.0: Merge development -> master

examples/aml-check/package-lock.json, examples/aml-check/package.json, examples/profile/package-lock.json, examples/profile/package.json
- Updated examples to use `3.5.0`
=> SDK-931: Update example packages

package.json, tests/aml_service/index.spec.js, tests/client/index.spec.js, tests/data_type/attribute.spec.js, tests/data_type/document.details.spec.js, tests/data_type/image.spec.js, tests/data_type/multi.value.spec.js, tests/profile_service/activity.details.spec.js, tests/profile_service/index.spec.js, tests/profile_service/profile.spec.js, tests/request/index.spec.js, tests/request/payload.spec.js, tests/yoti_common/anchor.processor.spec.js, tests/yoti_common/attribute.converter.spec.js, tests/yoti_common/index.spec.js
- Moved spec files into directories that reflect the files being tested
=> SDK-921: Organise test directory

src/profile_service/activity.details.js, src/profile_service/application.profile.js, src/profile_service/base.profile.js, src/profile_service/index.js, src/profile_service/profile.js, src/yoti_common/constants.js, src/yoti_common/index.js, tests/client/index.spec.js, tests/profile_service/activity.details.spec.js, tests/profile_service/application.profile.spec.js, tests/sample-data/profile-service/profile.json
- Added application profile getter to activity details
- Existing user profile and new application profile both extend new base profile
=> SDK-547: Add application profile getter to activity details

src/profile_service/base.profile.js, tests/profile_service/application.profile.spec.js, tests/profile_service/profile.spec.js, tests/sample-data/profile-service/application.profile.json, tests/sample-data/profile-service/profile.json
- `BaseProfile.getAttributes()` for user and application profiles
=> SDK-998: Add profile getter for all attributes

README.md
=> SDK-547: Add ApplicationProfile to README

README.md
=> SDK-1051: Update code snippets in README

examples/aml-check/package-lock.json, examples/profile/package-lock.json, examples/profile/package.json, package-lock.json
- Updated packages in `package-lock.json`
- Unpinned dependencies in `examples/profile/package.json`
- Updated packages in `examples/profile/package-lock.json`
- Updated packages in `examples/aml-check/package-lock.json`
=> SDK-1057: Update packages

README.md
- Updated README with new link to the developer docs
=> SDK-1086: Update README with new dev docs URL

examples/profile/index.js
- Removed withWantedAttributeByName example from the dynamic share example project
=> SDK-1112: Update dynamic share example project

.travis.yml
- Update all dependencies recursively before running tests - see: https://docs.npmjs.com/cli/update.html
=> SDK-930: Update dependencies recursively

package.json
=> SDK-1078: Update package.json version

.npmignore, package-lock.json, package.json, sonar-project.properties
- Ignore coverage directories and files in `.npmignore`
- Update version to `3.7.1` for release
=> SDK-1202: Ignore coverage directories and files

.npmignore, package-lock.json, package.json, sonar-project.properties
> Correction to #90 
- Ignore coverage directories and files in `.npmignore`
- Update version to `3.7.1` for release
=> Release 3.7.1

package-lock.json, package.json, sonar-project.properties, src/request/request.handler.js, tests/request/request.handler.spec.js
=> SDK-1203: Allow empty response body

.travis.yml, README.md, package-lock.json, package.json, src/aml_type/aml.address.js, src/yoti_common/validation.js, tests/aml_service/aml.address.spec.js, tests/aml_service/aml.profile.spec.js, tests/aml_service/index.spec.js
- Coveralls to Travis CI
- Test coverage for:
- `AmlProfile`
- `AmlAddress`
- AML check error responses
- `Validation.notNullOrEmpty()`
- `AmlAddress.setCountryCode()` validation
=> SDK-1239: Coveralls

package-lock.json, package.json, sonar-project.properties, src/data_type/date.js, tests/data_type/date.spec.js
* Merge hotfix into development
=> SDK-1255: Yoti Date Format (Hotfix → Development)

package-lock.json, package.json, src/dynamic_sharing_service/policy/wanted.attribute.js, tests/dynamic_sharing_service/dynamic.scenario.builder.spec.js, tests/dynamic_sharing_service/policy/dynamic.policy.builder.spec.js, tests/dynamic_sharing_service/policy/wanted.attribute.builder.spec.js
- Add derivation to payload only when specified
- npm audit fix (updated lock file)
=> SDK-1270: Optional Derivation

package-lock.json
- Updated packages: _handlebars_, _uglify-js_
=> Update packages: handlebars, uglify-js

src/data_type/date.js
> Correction to #100 
- Corrected JSDoc for date format
=> SDK-604: Correct date JSDoc

src/data_type/document.details.js, tests/data_type/document.details.spec.js
- Allow any character in DocumentDetails value
=> SDK-1445: Document Details Validation

.dependabot/config.yml
- update default_reviewers and default_assignees
=> SDK-1322: Update dependabot defaults

.dependabot/config.yml, .travis.yml
> Merge changes in master into development - we may want to wait for #144 to be merged into master before merging this into development
**Note: This should not be rebased when merging into development**
=> Merge master > development

config/yoti.js, tests/config/yoti.spec.js
- Support for standardised environment variables:
- `YOTI_API_URL`
- `YOTI_DOC_SCAN_API_URL`
=> SDK-1506: Add support for standardised environment variables

examples/doc-scan/src/controllers/error.controller.js
- Demo error message - fixes #142
=> SDK-1301: Correct demo error message

.travis.yml, README.md, package.json, sonar-project.properties
=> SDK-1392: Add SonarCloud to Travis

package-lock.json, package.json, src/request/request.builder.js, tests/client/doc.scan.client.spec.js, tests/doc_scan_service/doc.scan.service.spec.js, tests/dynamic_sharing_service/index.spec.js
=> SDK-1623: Update uuid

.travis.yml, package-lock.json
- Updated Travis audit threshold levels:
- Prod: all levels
- Dev: High and above
- Output flattened to prevent build failures due to "The job exceeded the maximum log length, and has been terminated."
- Output format example:
```
lodash (low) - No patch available - Prototype Pollution - https://npmjs.com/advisories/1523
```
- Updated `package-lock.json`
=> NA: NPM Audit

package-lock.json
- Updated `package-lock.json` with latest packages (fixes low risk lodash vulnerability)
=> NA: Update lodash

examples/profile/static/index.css, examples/profile/views/pages/dynamic-share.ejs, examples/profile/views/pages/index.ejs
=> Merge master → development

examples/doc-scan/views/pages/index.ejs
- Updated Doc Scan demo iframe to allow full screen
=> SDK-1684: Update Doc Scan demo iframe

.travis.yml
- Node 13 and 14 versions to Travis
=> NA: Node 13 / 14

examples/doc-scan/package.json, examples/doc-scan/src/controllers/media.controller.js, examples/doc-scan/views/pages/success.ejs
=> SDK-1750: Remove Face Map Demo

src/doc_scan_service/session/create/check/requested.document.authenticity.check.builder.js, src/doc_scan_service/session/create/check/requested.document.authenticity.config.js, tests/doc_scan_service/session/create/check/requested.document.authenticity.check.builder.spec.js
- Support manual check config for authenticity checks
=> SDK-1734: Support manual check config for authenticity checks

src/doc_scan_service/session/create/session.specification.builder.js, src/doc_scan_service/session/create/session.specification.js, src/doc_scan_service/session/retrieve/get.session.result.js, src/yoti_common/validation.js, tests/doc_scan_service/session/create/session.specification.builder.test.js, tests/doc_scan_service/session/retrieve/get.session.result.spec.js
- Support for biometric consent
=> SDK-1741: Biometric Consent

examples/doc-scan/src/controllers/index.controller.js, examples/doc-scan/views/pages/success.ejs
- ID document comparison to demo
- Biometric consent timestamp to demo (for #234)
=> SDK-1717: ID Document Comparison Demo

examples/doc-scan/views/pages/success.ejs, src/doc_scan_service/session/retrieve/page.response.js, tests/doc_scan_service/session/retrieve/page.response.spec.js
- Support for document page frames
=> SDK-1769: Document Page Frames

src/data_type/date.js, src/doc_scan_service/session/create/filters/document.filter.js, src/doc_scan_service/session/create/filters/document/document.restriction.builder.js, src/doc_scan_service/session/create/filters/document/document.restriction.js, src/doc_scan_service/session/create/filters/document/document.restrictions.filter.builder.js, src/doc_scan_service/session/create/filters/document/document.restrictions.filter.js, src/doc_scan_service/session/create/filters/orthogonal/country.restriction.js, src/doc_scan_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.builder.js, src/doc_scan_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.js, src/doc_scan_service/session/create/filters/orthogonal/type.restriction.js, src/doc_scan_service/session/create/filters/required.document.js, src/doc_scan_service/session/create/filters/required.id.document.builder.js, src/doc_scan_service/session/create/filters/required.id.document.js, src/doc_scan_service/session/retrieve/details.response.js, src/doc_scan_service/session/retrieve/text.extraction.task.response.js, src/doc_scan_service/support/supported.country.js, src/doc_scan_service/support/supported.document.js, src/doc_scan_service/support/supported.documents.response.js, src/request/request.handler.js
- Added missing strict directive
=> NA: Strict directive

examples/doc-scan/src/controllers/index.controller.js, examples/doc-scan/src/controllers/media.controller.js, package-lock.json, package.json, sonar-project.properties, src/doc_scan_service/doc.scan.service.js, tests/doc_scan_service/doc.scan.service.spec.js
- `204` media responses now return Media with no content
=> Release 3.13.1

examples/doc-scan/index.js, examples/doc-scan/src/controllers/index.controller.js, examples/doc-scan/views/pages/privacy-policy.ejs, src/doc_scan_service/session/create/sdk.config.builder.js, src/doc_scan_service/session/create/sdk.config.js, tests/doc_scan_service/session/create/sdk.config.builder.test.js
- Support for custom privacy policy URL
=> SDK-1820: Privacy Policy URL

src/doc_scan_service/session/retrieve/get.session.result.js, src/doc_scan_service/session/retrieve/third.party.identity.check.response.js, tests/doc_scan_service/session/retrieve/get.session.result.spec.js
Implement third party identity resource retrieving from a session
Implemented unit test for session retrieving with third party identity checks
=> HUB-3812 Implement third party identity resource retrieving from a session

.github/workflows/sonar.yaml, .github/workflows/tests.yaml, examples/aml-check/package.json, examples/doc-scan/.gitignore, examples/doc-scan/package-lock.json, examples/doc-scan/package.json, examples/profile/package.json
Migrating the tests run in Travis to Github Actions (work from @emmas-yoti)
=> SDK-1857 migrate to GitHub actions

.github/workflows/tests.yaml, README.md, package-lock.json, package.json, sonar-project.properties, src/doc_scan_service/doc.scan.constants.js, src/doc_scan_service/session/create/notification.config.builder.js, src/doc_scan_service/session/create/notification.config.js, src/yoti_common/validation.js, tests/doc_scan_service/session/create/notification.config.builder.test.js, tests/doc_scan_service/session/create/notification.config.test.js, tests/doc_scan_service/session/create/session.specification.builder.test.js, tests/yoti_common/validation.spec.js
**new:** Notification configuration with new Auth Type (`BASIC`, `BEARER`)
**chore:** Fix y18n (security Prototype Pollution) (from 4.0.0 to 4.0.3)
=> Release 3.16.0

src/doc_scan_service/session/create/session.specification.builder.js, src/doc_scan_service/session/create/session.specification.js, tests/doc_scan_service/session/create/session.specification.builder.test.js, tests/doc_scan_service/session/create/session.specification.test.js
* Added support for the session_deadline property in the session specification
* Added a test case for the new property
=> SDK-1983 Add support for session deadline

src/dynamic_sharing_service/dynamic.scenario.builder.js, src/dynamic_sharing_service/dynamic.scenario.js, tests/dynamic_sharing_service/dynamic.scenario.builder.spec.js
Updated dynamic.scenario and its builder to expose withSubject(), which then set `subject` in the scenario.
=> SDK-2084 support subject in scenario

.github/workflows/tests.yaml, package-lock.json, package.json
- Remove audit-ci exception for node-forge
- Update node-forge version
=> SDK-2173 Upgrade node forge

package-lock.json, package.json, src/request/payload.js, src/yoti_common/index.js, tests/yoti_common/attribute.converter.spec.js
Replace `safe-buffer` usages with Node's built in `Buffer`
=> SDK-2177 Remove usages of Buffer from safe-buffer

package-lock.json, package.json, src/client/yoti.client.js, src/yoti_common/index.js
Replaced usages of `node-rsa` with Node's `crypto`
=> SDK-2176 Remove node rsa

examples/idv/index.js, examples/idv/src/controllers/config.controller.js, examples/idv/src/controllers/index.controller.js, examples/idv/src/controllers/index.js, examples/idv/views/pages/config.ejs, examples/idv/views/pages/index.ejs
Updated the IDV example to retrieve and display the session configuration in a new tab.
=> SDK-1985 fetching session config support example

examples/digital-identity/controllers/share.session.controller.js, examples/digital-identity/index.js, src/client/digital.identity.client.js, src/digital_identity_service/index.js, src/digital_identity_service/share.session.fetch.result.js, tests/client/digital.identity.client.spec.js, tests/digital_identity_service/index.spec.js, tests/digital_identity_service/share.session.fetch.result.spec.js
=> SDK-2243 share v2 retrieve session

examples/idv/views/pages/success.ejs, src/idv_service/session/retrieve/expanded.document.fields.response.js, src/idv_service/session/retrieve/id.document.resource.response.js, tests/idv_service/session/retrieve/expanded.document.fields.response.spec.js, tests/idv_service/session/retrieve/id.document.resource.response.spec.js
Added support for expanded_document_fields media.
=> SDK-2337 Support expanded document fields media

examples/idv/src/controllers/use-cases/allow.expired.document.check.controller.js, examples/idv/src/controllers/use-cases/document.comparison.check.controller.js, examples/idv/src/controllers/use-cases/index.js, examples/idv/src/routes/use-cases-router.js, examples/idv/src/useCases.js, src/idv_service/session/create/filters/document/document.restrictions.filter.builder.js, src/idv_service/session/create/filters/document/document.restrictions.filter.js, src/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.builder.js, src/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.js, tests/idv_service/session/create/filters/document/document.restrictions.filter.builder.spec.js, tests/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.builder.spec.js
Added `allow_expired_documents` to payload corresponding to **DocumentRestrictionsFilter** and **OrthogonalRestrictionsFilter**.
=> SDK-2187 IDV to allow or not expired documents

src/client/idv.client.js, src/idv_service/idv.service.js, src/idv_service/support/supported.document.js, tests/client/idv.client.spec.js, tests/idv_service/idv.service.spec.js, tests/idv_service/support/supported.documents.response.spec.js
Added support for non latin documents when fetch supported documents.
=> SDK-2045 Non latin documents support when fetching supported docs

examples/idv/src/controllers/use-cases/allow.non.latin.document.check.controller.js, examples/idv/src/controllers/use-cases/index.js, examples/idv/src/routes/use-cases-router.js, examples/idv/src/useCases.js
Added the example to check the non latin document support.
=> SDK-2027 non latin documents support example

examples/digital-identity/controllers/profile.controller.js, examples/idv-identity-checks/views/pages/partials/identity-profile.ejs
Updated examples of Digital Identity and IDV flows to surface and display the errors raised during identity profile checks.
=> Release support - examples update
