src/profile_service/index.js

`src/profile_service/index.js`
`Buffer.from` is not avaliable in Node < 5.10
https://nodejs.org/dist/latest-v7.x/docs/api/buffer.html#buffer_class_method_buffer_from_buffer
Changing it to `new Buffer` allows users with older node versions to use the SDK.
Fixes issue #3

Replace `Buffer.from` with `new Buffer`

---

README.md
example/simple-login/index.js
example/simple-login/package.json
package.json
src/profile_service/index.js

Initial PR, once this is approved I can upload the new package, and then update the example project to use this new package. 
I also just added the instructions for installing the dependencies and running the tests.
@Alttaf - is bumping the version to 2.0.0 ok? Based on semantic versioning, I thought this extra header is an incompatible API change, and so 1.1.0 isn't appropriate.
I also just highlighted a part of the instructions in bold, as I missed this when I was scanning through, and it was quite important!

[SDK-115]: Added X-SDK identifier to HTTP header sent with API requests

---

README.md
package.json
src/profile_service/index.js

I changed the README to have the version number as "yoti" : "x.x.x" to prevent having to change this each time. Would you say this makes sense? I'll update on npm, and then install to the example project once this is approved.

[SDK-128]: Changed X-SDK to X-Yoti-SDK and updated package

---

example/simple-login/package-lock.json
example/simple-login/package.json

Also committed package-lock.json.
I'm thinking we should do this based on [npm docs](https://docs.npmjs.com/files/package-lock.json), [SO Answer 1](https://stackoverflow.com/questions/44297803/package-lock-json-role) and [SO Answer 2](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5)
package-lock.json file will be updated every time you use npm install since NPM 5.1. So we'd either be updating it every time before checking in, or discarding/ignoring it from source control every time.
Listed as the benefits are:
- Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
- Provide a facility for users to "time-travel" to …

[SDK-128]: Updated example project to use new package

---

.npmignore
package.json

Nothing was required for example project due to the package.json file for that specifying private

[SDK-167]: Excluded test folder from published package using .npmignore

---

src/request/index.js
tests/request.spec.js

- Sending `package.json` version in `X-Yoti-SDK-Version`, e.g. `3.2.0`
> I can change this to use a constant defined in `src/request/index.js` if that's preferable?

SDK-670: Send X-Yoti-SDK-Version header

---

src/data_type/image.jpeg.js
src/data_type/image.js
src/data_type/image.png.js
src/proto-root/proto.attribute.list.js
src/proto-root/utils.js
src/yoti_common/attribute.converter.js
src/yoti_common/constants.js
tests/data-type.image.spec.js

- _Abstract_ `Image` class providing methods:
- _Abstract_ `getMimeType()`
- `getBase64Content()`
- `getContent()`
- `ImageJpeg`/`ImagePng` classes extend `Image`, and implement `getMimeType()`
- Kept `getBase64SelfieUri()`, but is now using `Image::getBase64Content()`
- `selfie` property continues to return image content (rather than new `Image` object), but is now using `Image::getContent()`

SDK-584: Image object

---

README.md
examples/profile/index.js
examples/profile/views/pages/profile.ejs
src/profile_service/index.js
tests/client.spec.js
tests/profile-service.spec.js

- Introduced new `getRememberMeId()` method
- Documented activity details methods and `@deprecated` `getUserId()`
- Update example project to use `getRememberMeId()`

SDK-568: Deprecate getUserId()

---

package.json
src/request/index.js
tests/request.spec.js

- Prefixing version with SDK identifier
- Also upped minimum `base64-url` requirement to include [npm audit fixes](https://github.com/joaquimserafim/base64-url/releases/tag/v2.2.1)

SDK-909: Include prefix in SDK version

---

src/yoti_common/attribute.converter.js
tests/yoti-common.attribute.converter.spec.js

- Returns UTF-8 encoded string for unknown and undefined content types
>_Note: In order to test log messages we need to introduce a new dependency to spy on the console log calls, such as Chai Spy, Jasmine, Sinon, Jest. I'll open a ticket to look at these, [Jest](https://www.npmjs.com/package/jest) in particular, which is very popular, allows for spying on objects and seems straight forward to switch over to_

SDK-897: Return unknown and undefined content types as string

---

src/profile_service/activity.details.js
tests/profile_service/activity.details.spec.js
tests/profile_service/index.spec.js

- `ActivityDetails.getTimestamp()`

SDK-990: Add timestamp getter to activity details

---

src/data_type/date.js
src/data_type/signed.timestamp.js
src/yoti_common/anchor.processor.js
tests/data_type/anchor.spec.js
tests/data_type/date.spec.js
tests/data_type/signed.timestamp.spec.js
tests/yoti_common/anchor.processor.spec.js

- `YotiDate` extending `Date`, providing methods:
- `getMicroseconds()` - Number between 0 and 999999, representing the microseconds.
- `getMicrosecondTimestamp()` - Returns ISO 8601 UTC timestamp with microseconds.
- `getMicrosecondTime()` - Time with microseconds.
- `YotiSignedTimeStamp.getTimestamp()` now returns `YotiDate`:
- `timestamp.getTimestamp() instanceof Date` **>** `TRUE` _(Unchanged)_
- `timestamp.getTimestamp() instanceof YotiDate` **>** `TRUE` _(New)_
- `typeof timestamp.getTimestamp()` **>** `object` _(Unchanged)_
- `timestamp.getTimestamp().constructor.name` **>** `YotiDate` _(was `Date`)_
_Should this be considered a breaking change?_

 SDK-1000: Return date object with microsecond accuracy

---

src/profile_service/base.profile.js
tests/profile_service/application.profile.spec.js
tests/profile_service/profile.spec.js

>Correction to #69 
- Returns all attributes as `{Object.<string, Attribute>}`

SDK-998: Return all attributes as Object

---

tests/client/index.spec.js
tests/data_type/attribute.spec.js

>Correction to #67 
- Correction to `Attribute` test - constructor should be passed a key/value Object, but was being passed an array - `concat()` can append both single values and arrays, so the resulting anchor array is the same.
- Additional test coverage for unknown anchors in the existing sample test data.

SDK-660: Additional test coverage for unknown anchors

---

README.md

- SDK version < 3 example from README
- Using lowercase `yoti.` in all snippets to match `const yoti = require('yoti')`

SDK-725: Update code snippets in README

---

examples/profile/views/pages/profile.ejs
src/data_type/age.verification.js
src/profile_service/base.profile.js
src/profile_service/profile.js
src/yoti_common/age.js
src/yoti_common/validation.js
tests/data_type/age.verification.spec.js
tests/profile_service/profile.spec.js
tests/sample-data/profile-service/profile.json

- `AgeVerification`
- `.getCheckType()`
- `.getAge()`
- `.getResult()`
- `.getAttribute()`
- `BaseProfile`
- `.findAttributesStartingWith()`
- `Profile`
- `.getAgeVerifications()`
- `.findAgeOverVerification(age)`
- `.findAgeUnderVerification(age)`
- `.findAgeVerification(type, age)` - intended to be used by _findAgeOverVerification_/_findAgeUnderVerification_
- `.findAllAgeVerifications()`
- `Validation.matchesPattern()`
- `Profile.getAgeVerified()`
- `Age` found at _yoti_common/age_

SDK-578: Add support for multiple age verifications

---

src/profile_service/profile.js
tests/profile_service/profile.spec.js

- `Profile.getPostalAddress()` will now return formatted address from structured address attribute when postal address is `null`.

SDK-581: Postal Address

---

examples/profile/views/pages/dynamic-share.ejs
examples/profile/views/pages/profile.ejs
src/data_type/document.details.js
tests/data_type/document.details.spec.js

- `DocumentDetails.getIssuingAuthority()`

SDK-1072: Add issuing authority getter

---

package-lock.json
src/data_type/document.details.js
tests/data_type/document.details.spec.js

- JSDocs for optional document details
- Removed redundant `this.validateData(value);` _(already called in `parseFromValue`)_
- NPM audit fix _(updated package-lock.json)_

SDK-604: Correct Document Details docs & npm audit fix

---

src/request/request.builder.js
src/request/request.handler.js
src/request/request.js
src/request/response.js
tests/request/request.builder.spec.js
tests/request/request.handler.spec.js
tests/request/request.spec.js
tests/request/response.spec.js

> Correction to #99 
- _./request/request.handler_ `execute()`
- `YotiResponse.getParsedResponse()`
- Returns `Buffer` for binary responses
- For non-empty response text
- Returns `response.body` when `Content-Type` **is** set
- Returns `JSON.parse(response.text)` when `Content-Type` is **not** set
- Any other response is `null`
- _./request/request.handler_ `execute(buffer = false)`
- Optional `buffer` argument that defaults to `false`. This allows responses to be returned as a `Buffer` for binary content types.
- `YotiResponse.getBody()` will return _string_ or _Buffer_ for binary responses - this allows the body to be parsed outside the request handler
- Unnecessary `|| {},` for query params as the property is set to `{}` in the constructor.

SDK-1203: Binary response

---

package-lock.json
package.json
sonar-project.properties
src/request/request.builder.js
src/request/request.handler.js
src/request/request.js
src/request/response.js
tests/request/request.builder.spec.js
tests/request/request.handler.spec.js
tests/request/request.spec.js
tests/request/response.spec.js

- `YotiResponse.getParsedResponse()` returns
- `Buffer` for binary responses
- Parsed _JSON_ for _JSON_ responses
- `null` for empty responses
- `YotiRequest.execute(buffer = false)`
- Optional `buffer` argument that _(default value: `false`)_.
- Set `true` to return binary content types as a `Buffer`.
- `YotiResponse.getBody()`
- Returns _string_ for text responses
- Returns _Buffer_ for binary responses

Release 3.7.2

---

src/profile_service/index.js
src/request/index.js
src/request/request.builder.js
tests/client/index.spec.js
tests/request/request.builder.spec.js

- `X-Yoti-Auth-Key` header is only provided to profile endpoint
- Default `Content-Type` header is only added when payload is provided

SDK-1208: Request Builder Headers

---

package.json

- Compatible Node engine in _package.json_ to `>=6`

SDK-1236: Supported Node version

---

package-lock.json
package.json
sonar-project.properties
src/data_type/date.js
tests/data_type/date.spec.js

* Updated `YotiDate` to return microsecond time format with minutes zero padded

SDK-1255: Fix YotiDate format

---

src/dynamic_sharing_service/policy/wanted.attribute.js
tests/dynamic_sharing_service/policy/wanted.attribute.builder.spec.js

- Preventing empty wanted attribute names

SDK-1279: Prevent empty wanted attribute name

---

src/request/request.handler.js
src/request/response.js
tests/request/request.handler.spec.js
tests/request/response.spec.js

- `YotiResponse.getHeaders()` returns `{Object.<string, string>}` map of headers

SDK-1277: Add headers getter to response object

---

.gitignore
src/data_type/date.js
tests/data_type/date.spec.js

- `YotiDate.fromDateString()` now supports microsecond accuracy
- `YotiDate.constructor()` now supports signed microsecond timestamps, e.g. `-1571630945999999` will have **1** microsecond
- Rounding when converting microseconds to `YotiDate`

SDK-1368: Support microsecond accuracy using fromDateString()

---

.dependabot/config.yml
.gitignore
package-lock.json
package.json
sonar-project.properties
src/data_type/date.js
src/data_type/document.details.js
tests/data_type/date.spec.js
tests/data_type/document.details.spec.js

- Document details parsing: now accommodates more values _(including redacted Aadhar numbers)_
- `YotiDate.fromDateString()` now supports microsecond accuracy
- `YotiDate.constructor()` now supports signed microsecond timestamps, e.g. `-1571630945999999` will have **1** microsecond
- Rounding when converting microseconds to `YotiDate`

Release 3.8.1

---

sandbox/profile/request/attribute/anchor.js
src/data_type/date.js
tests/data_type/date.spec.js
tests/sandbox/request/attribute/anchor.spec.js
tests/sandbox/request/attribute/attribute.spec.js
tests/sandbox/request/attribute/derivation/age.verification.spec.js
tests/sandbox/request/token.spec.js

- Sandbox anchors now use `YotiDate`
- `YotiDate.getMicrosecondUnixTimestamp()` to get the microsecond Unix timestamp from a Yoti date

SDK-1476: Use YotiDate for sandbox anchors

---

.travis.yml

- Audit production dependencies only (whilst we support Node 6)

NA: NPM Audit

---

src/doc_scan_service/session/retrieve/check.response.js
src/doc_scan_service/session/retrieve/generated.check.response.js
src/doc_scan_service/session/retrieve/liveness.resource.response.js
src/doc_scan_service/session/retrieve/task.response.js
tests/doc_scan_service/session/retrieve/authenticity.check.response.spec.js
tests/doc_scan_service/session/retrieve/check.response.spec.js
tests/doc_scan_service/session/retrieve/face.match.check.response.spec.js
tests/doc_scan_service/session/retrieve/generated.check.response.spec.js
tests/doc_scan_service/session/retrieve/generated.text.data.check.response.spec.js
tests/doc_scan_service/session/retrieve/get.session.result.spec.js
tests/doc_scan_service/session/retrieve/id.document.resource.response.spec.js
tests/doc_scan_service/session/retrieve/liveness.check.response.spec.js
tests/doc_scan_service/session/retrieve/liveness.resource.response.spec.js
tests/doc_scan_service/session/retrieve/resource.container.spec.js
tests/doc_scan_service/session/retrieve/resource.response.spec.js
tests/doc_scan_service/session/retrieve/task.response.spec.js
tests/doc_scan_service/session/retrieve/text.extraction.task.response.spec.js
tests/doc_scan_service/session/retrieve/zoom.liveness.resource.response.spec.js

- `CheckResponse.getType()`
- `TaskResponse.getType()`
- `LivenessResourceResponse.getLivenessType()`
- `GeneratedCheckResponse.getType()`

SDK-1549: Add type to responses

---

package-lock.json
package.json

> Amends https://github.com/getyoti/yoti-node-sdk/pull/147
>
> Although our Node 6 compatibility test passed with SuperAgent v5, it is officially only compatible with `>= 7`. We should use a version officially compatible with Node 6
- Changed SuperAgent version to v4, which is officially compatible with Node `>= 6`

NA: Downgrade superagent

---

.travis.yml
package-lock.json
package.json

- Running `npm audit` for all packages (including _devDependencies_)
- Updated `package-lock.json`
- Coveralls dev dependency (replaced by SonarCloud in #180)

SDK-1626: NPM audit

---

src/doc_scan_service/doc.scan.error.js
tests/doc_scan_service/doc.scan.error.spec.js
tests/doc_scan_service/doc.scan.service.spec.js

- API error message is now included in `DocScanError` message. Falls back on the message of the error it is wrapping (e.g. "Bad Request")
This follows similar format to AML errors:
```
{CODE} - {MESSAGE}
```
```
{CODE} - {MESSAGE}: {PROPERTY} "{PROPERTY_MESSAGE}", {OTHER_PROPERTY} "{OTHER_PROPERTY_MESSAGE}"
```

SDK-1579: DocScanError message

---

.github/dependabot.yml

- Went into `master` before `development` as we want this to stop dependabot running daily now, and don't want to have to wait for the privacy policy release (currently in development)

NA: Update dependabot config

---

examples/doc-scan/src/controllers/index.controller.js
examples/doc-scan/views/pages/success.ejs

> Add TPI check to the example when creating the session and retrieving the session report on the success page

HUB-3813 Add TPI check to the Doc scan example when creating and retrieving the session

---

.github/workflows/tests.yaml

Removed from the **tests** Github action step `npm audit --audit-level=high` as it runs after the `npm audit --production` one, which is already a blocking step, that already provides the list of dependencies to be updated (but only for prod).

Changed tests GitHub action 

---

src/doc_scan_service/doc.scan.constants.js
src/doc_scan_service/session/create/notification.config.builder.js
src/doc_scan_service/session/create/notification.config.js
src/yoti_common/validation.js
tests/doc_scan_service/session/create/notification.config.builder.test.js
tests/doc_scan_service/session/create/notification.config.test.js
tests/doc_scan_service/session/create/session.specification.builder.test.js
tests/yoti_common/validation.spec.js

Allows the NotificationConfig to have a authorisation type of either `BASIC` or `BEARER`.
The NotificationConfigBuilder exposes two methods `withAuthTypeBasic()` and `withAuthTypeBearer()`
All CI tests pass

SDK-1836 New auth-type (BEARER)

---

.github/workflows/tests.yaml

* Fix GitHub actions: lint examples test should run with Node 14
* Also print npm and node version

Fix GitHub actions (lint examples to run with Node 14)

---

examples/doc-scan/src/controllers/index.controller.js
src/doc_scan_service/session/create/sdk.config.builder.js
src/doc_scan_service/session/create/sdk.config.js
tests/doc_scan_service/session/create/sdk.config.builder.test.js

* Added support for the allow_handoff property in the SDK configuration
* Updated test to include the new method
* Incorporated it into the main example

SDK-1996 Add support for mobile handoff

---

examples/doc-scan/src/controllers/index.controller.js
src/doc_scan_service/doc.scan.constants.js
src/doc_scan_service/session/create/sdk.config.builder.js
src/doc_scan_service/session/create/sdk.config.js
tests/doc_scan_service/session/create/sdk.config.builder.test.js

Added 3 methods in **SdkConfigBuilder** to allow setting up the retries of ID Document text extraction by category.
```
withIdDocumentTextExtractionCategoryRetries(category, retries)
withIdDocumentTextExtractionReclassificationRetries(retries)
withIdDocumentTextExtractionGenericRetries(retries)
```
The values are expressed in the sdk config within the `attempts_configuration` field:
```
// sdk config
{
[...]
attempts_configuration: {
ID_DOCUMENT_TEXT_DATA_EXTRACTION: {
GENERIC: 3,
RECLASSIFICATION: 2,
},
},
}
```

SDK-1890 add attempts configuration

---

src/doc_scan_service/session/create/check/requested.custom.account.watchlist.advanced.ca.config.js
src/doc_scan_service/session/retrieve/custom.account.watchlist.ca.search.config.response.js
tests/doc_scan_service/session/create/check/requested.watchlist.advanced.ca.builder.spec.js
tests/doc_scan_service/session/retrieve/custom.account.watchlist.ca.search.config.response.spec.js

Made `tags` optional in the _RequestedCustomAccountWatchlistAdvancedCaConfig_ and the _CustomAccountWatchlistCaSearchConfigResponse_, so when not specified by user in the request, no empty object is sent by default anymore, and when retrieving the config in the response, it is no longer assumed that the `tags` must be there.

SDK-2049 bug fix optional tags in CustomAccountWatchlistCaSearchConfig

---

.github/workflows/tests.yaml

Changed the actions "Unit Tests" to use 'audit-ci' so 'node-forge' can be bypassed.

[CI] Exclude 'node-forge' from audit

---

src/dynamic_sharing_service/policy/dynamic.policy.builder.js
src/dynamic_sharing_service/policy/dynamic.policy.js
tests/dynamic_sharing_service/policy/dynamic.policy.builder.spec.js

Updated dynamic.policy and its builder to expose `withIdentityProfileRequirements()`, which then set `identityProfileRequirements` in the policy.
~(includes #304, branch to be rebased once it is merged)~ now rebased

SDK-2074 support identity profile requirements in dynamic policy

---

src/profile_service/profile.js
src/yoti_common/constants.js
tests/profile_service/profile.spec.js
tests/sample-data/profile-service/profile.json

Updated profile_service so the add new method `profile.getIdentityProfileReport()`
~(includes #305 , to be rebased once merged)~

SDK-2079 retrieve identity profile requirements attribute

---

src/data_type/attribute.js
src/profile_service/base.profile.js
src/proto-root/proto.attribute.list.js
tests/data_type/attribute.spec.js
tests/profile_service/profile.spec.js
tests/proto-root/index.spec.js

Updated the Attribute so it assigns a field `id` if present within raw attribute data argument.
Added in BaseProfile the method getAttributeById()
Amended proto.attribute.list so the ephemeralId field from attribute proto is read and assign to the raw attribute id field.

SDK-2091 get attribute by id

---

src/profile_service/activity.details.js
tests/profile_service/activity.details.spec.js

Modified in profile_service activity.details.js, so it exposes a getErrorDetails() method, that returns an object corresponding to the 'error_details' from the response.
```javascript
// given a response with failure
{
"session_data": { ... },
"receipt": {
sharing_outcome: "FAILURE"
},
"error_details": { 
"error_code": "the-error-code-from-the-failure-receipt"
"description": "some error desc"
}
}
// usage:
const activityDetails = await getReceipt(token, pem, sdkId)
const outcome = activityDetails.getOutcome()
console.log(outcome) // FAILURE
const errorDetails = activityDetails.getErrorDetails()
console.log(errorDetails)
// {
//   errorCode: "the-error-code-from-the-failure-receipt"
//   description: "some error desc"
// }
```

SDK-2142 Surface error details in share receipt response

---

.github/workflows/tests.yaml
.travis.yml
package-lock.json
package.json

Updated:
package.json to drop support for versions older than 14.
tests.yaml to drop testing for versions older than 14 and test for node versions 14, 16 and 18 only.
.travis.yaml to drop testing for versions older than 14 and test for node versions 14, 16 and 18 only.

SDK-2171 Deprecate old node support

---

.github/dependabot.yml
.github/workflows/tests.yaml
audit-ci.jsonc
examples/aml-check/package-lock.json
examples/aml-check/package.json
examples/digital-identity/package-lock.json
examples/digital-identity/package.json
examples/idv-identity-checks/package-lock.json
examples/idv-identity-checks/package.json
examples/idv/package-lock.json
examples/idv/package.json
examples/profile-identity-checks/package-lock.json
examples/profile-identity-checks/package.json
examples/profile/package-lock.json
examples/profile/package.json
package-lock.json
package.json

Dependencies vulnerabilities fix - (via npm audit fix)
Updated manually dependencies:
- node-forge => 1.3.1
- eslint-plugin-jest => 7.2.4
Updated manually dev dependencies:
- eslint => 8.43.0
- eslint-plugin-jest => 27.2.2
- jest => 29.5.0
Added `audit-ci` and configured it to allow [GHSA-c2qf-rxjj-qqgw](https://github.com/advisories/GHSA-c2qf-rxjj-qqgw)

Dependencies fix 28-06-2023

---

examples/idv/src/controllers/index.controller.js
src/idv_service/idv.constants.js
src/idv_service/session/create/sdk.config.builder.js
src/idv_service/session/create/sdk.config.js
tests/idv_service/session/create/sdk.config.builder.test.js

Added `biometricConsentFlow` to the SDK config by using `withEarlyBiometricConsentFlow` or `withJustInTimeBiometricConsentFlow` methods.

SDK-2310 Add biometric consent flow

---

examples/idv/src/controllers/index.controller.js
src/idv_service/session/create/check/requested.watchlist.advanced.ca.config.js
src/idv_service/session/create/task/requested.text.extraction.config.js
src/idv_service/session/create/task/requested.text.extraction.task.builder.js
tests/idv_service/session/create/task/requested.text.extraction.task.builder.spec.js

Added `withCreateExpandedDocumentFields` method to set a boolean value for `createExpandedDocumentFields` for the `RequestedTextExtractionTask`.

SDK-2338 enabling expanded document fields

---

src/idv_service/session/create/filters/document/document.restrictions.filter.builder.js
src/idv_service/session/create/filters/document/document.restrictions.filter.js
src/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.builder.js
src/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.js
tests/idv_service/session/create/filters/document/document.restrictions.filter.builder.spec.js
tests/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.builder.spec.js

Added `withAllowNonLatinDocuments` for `OrthogonalRestrictionsFilterBuilder`.

SDK-2043 non latin docs support for session creation

---

src/idv_service/session/retrieve/configuration/capture/document/supported.document.response.js
tests/idv_service/session/retrieve/configuration/capture/document/supported.country.response.spec.js
tests/idv_service/session/retrieve/configuration/capture/document/supported.document.response.spec.js

Expose `is_strictly_latin` property in the supported documents of the session configuration.

SDK-2044 Expose is_strictly_latin property

---

examples/idv/src/controllers/use-cases/allow.non.latin.document.check.controller.js
examples/idv/src/controllers/use-cases/index.js
examples/idv/src/routes/use-cases-router.js
examples/idv/src/useCases.js
src/client/idv.client.js
src/idv_service/idv.service.js
src/idv_service/session/create/filters/document/document.restrictions.filter.builder.js
src/idv_service/session/create/filters/document/document.restrictions.filter.js
src/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.builder.js
src/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.js
src/idv_service/session/retrieve/configuration/capture/document/supported.document.response.js
src/idv_service/support/supported.document.js
tests/client/idv.client.spec.js
tests/idv_service/idv.service.spec.js
tests/idv_service/session/create/filters/document/document.restrictions.filter.builder.spec.js
tests/idv_service/session/create/filters/orthogonal/orthogonal.restrictions.filter.builder.spec.js
tests/idv_service/session/retrieve/configuration/capture/document/supported.country.response.spec.js
tests/idv_service/session/retrieve/configuration/capture/document/supported.document.response.spec.js
tests/idv_service/support/supported.documents.response.spec.js

SDK-2027 non latin documents support

---

.github/workflows/tests.yaml

- added compatibility test for node 20
- updated the Github actions to @v4 (remove annotations warning, see [list of annotations](https://github.com/getyoti/yoti-node-sdk/actions/runs/7559170947))

Maintenance: compatibility for node 20 checks

---

examples/profile-identity-checks/controllers/report.controller.js
examples/profile-identity-checks/controllers/share.url.controller.js
examples/profile-identity-checks/views/pages/identity-profile-report.ejs
examples/profile-identity-checks/views/pages/index.ejs
src/dynamic_sharing_service/policy/dynamic.policy.builder.js
src/dynamic_sharing_service/policy/dynamic.policy.js
tests/dynamic_sharing_service/policy/dynamic.policy.builder.spec.js
types/src/dynamic_sharing_service/policy/dynamic.policy.builder.d.ts
types/src/dynamic_sharing_service/policy/dynamic.policy.d.ts

Modified src/dynamic_sharing_service:
- added to DynamicPolicyBuilder the method .withAdvancedIdentityProfileRequirements()
- updated DynamicPolicy constructor to accept an additional parameter (advancedIdentityProfileRequirements) and to include it in the payload as 'advanced_identity_profile_requirements'.
Updated examples/profile-identity-checks:
- added an new case to demo the advanced identity profile requirements
- added extraction/display of 'verification_reports' and 'authentication_reports'

SDK-2366 Advanced Identity Profile in share v1

---

examples/digital-identity/controllers/profile.controller.js
examples/digital-identity/controllers/share.controller.js
examples/digital-identity/static/index.css
examples/digital-identity/views/pages/profile-with-identity.ejs
examples/digital-identity/views/pages/share.ejs
src/digital_identity_service/policy/policy.builder.js
src/digital_identity_service/policy/policy.js
tests/digital_identity_service/policy/policy.builder.spec.js
types/src/digital_identity_service/policy/policy.builder.d.ts
types/src/digital_identity_service/policy/policy.d.ts

Modified src/digital_identity_service:
added to PolicyBuilder the method .withAdvancedIdentityProfileRequirements()
updated Policy constructor to accept an additional parameter (advancedIdentityProfileRequirements) and to include it in the payload as 'advanced_identity_profile_requirements'.

SDK-2417 advanced identity profile share v2

---

examples/digital-identity/controllers/profile.controller.js
examples/digital-identity/controllers/share.controller.js
examples/digital-identity/static/index.css
examples/digital-identity/views/pages/profile-with-identity.ejs
examples/digital-identity/views/pages/share.ejs
examples/profile-identity-checks/controllers/report.controller.js
examples/profile-identity-checks/controllers/share.url.controller.js
examples/profile-identity-checks/views/pages/identity-profile-report.ejs
examples/profile-identity-checks/views/pages/index.ejs
src/digital_identity_service/policy/policy.builder.js
src/digital_identity_service/policy/policy.js
src/dynamic_sharing_service/policy/dynamic.policy.builder.js
src/dynamic_sharing_service/policy/dynamic.policy.js
tests/digital_identity_service/policy/policy.builder.spec.js
tests/dynamic_sharing_service/policy/dynamic.policy.builder.spec.js
types/src/digital_identity_service/policy/policy.builder.d.ts
types/src/digital_identity_service/policy/policy.d.ts
types/src/dynamic_sharing_service/policy/dynamic.policy.builder.d.ts
types/src/dynamic_sharing_service/policy/dynamic.policy.d.ts

Modified src/dynamic_sharing_service:
- added to DynamicPolicyBuilder the method .withAdvancedIdentityProfileRequirements()
- updated DynamicPolicy constructor to accept an additional parameter (advancedIdentityProfileRequirements) and to include it in the payload as 'advanced_identity_profile_requirements'.
Updated examples/profile-identity-checks:
- added an new case to demo the advanced identity profile requirements
- added extraction/display of 'verification_reports' and 'authentication_reports'
Add advanced identity profile in digital-identity
Updated examples/digital-identity:
- Added extra case for advanced identity profile in digital identity example

SDK-2365 Support Advanced Identity Profile

---

src/idv_service/session/retrieve/identity.profile.failure.reason.response.js
src/idv_service/session/retrieve/identity.profile.response.js
tests/idv_service/session/retrieve/identity.profile.response.spec.js
types/src/idv_service/session/retrieve/identity.profile.failure.reason.response.d.ts
types/src/idv_service/session/retrieve/identity.profile.response.d.ts

Surface the 'requirements not met details' within the IdentityProfile FailureReasonResponse.
Given a session (with identity profile requirement) is completed and retrieved:
```ts
const sessionResult = await idvClient.getSession(sessionId);
const identityProfile = sessionResult.getIdentityProfile();
if (identityProfile) {
const failureReason = identityProfile.getFailureReason();
if (failureReason) {
const reasonCode = failureReason.getReasonCode(); // string
const requirementsNotMetDetails = failureReason.getRequirementsNotMetDetails(); // Array of RequirementsNotMetDetail
/*
RequirementsNotMetDetail shape as follows:
{
failureType, //string
documentType, //string
documentCountryIsoCode, //string
auditId, //string
details, //string
}
*/
}
}
```

SDK-2372 - IDV: surface identity profile failure reason details

---

src/digital_identity_service/index.js

Removed extraneous query params "appId" in requests made by digital_identity_service

SDK-2455 remove extraneous query params "appId" in share v2 requests

---

src/idv_service/session/retrieve/identity.profile.failure.reason.response.js
src/idv_service/session/retrieve/identity.profile.report.schemes.compliance.response.js
src/idv_service/session/retrieve/identity.profile.requirements.not.met.detail.response.js
tests/idv_service/session/retrieve/identity.profile.report.schemes.compliance.response.spec.js
tests/idv_service/session/retrieve/identity.profile.requirement.not.met.detail.response.spec.js
tests/idv_service/session/retrieve/identity.profile.response.spec.js
types/src/idv_service/session/retrieve/identity.profile.failure.reason.response.d.ts
types/src/idv_service/session/retrieve/identity.profile.report.schemes.compliance.response.d.ts
types/src/idv_service/session/retrieve/identity.profile.requirements.not.met.detail.response.d.ts

Created class `IdentityProfileRequirementsNotMetDetailResponse` to parse/expose the RequirementsNotMetDetail object.
Updated `IdentityProfileFailureReasonResponse` to use `IdentityProfileRequirementsNotMetDetailResponse`
Modified `IdentityProfileReportSchemesComplianceResponse` to include conditionally field _requirementsNotMetDetails_, as a list of `IdentityProfileRequirementsNotMetDetailResponse`

SDK-2453 include requirements_not_met_details in scheme compliance

---

src/idv_service/session/create/sdk.config.builder.js
src/idv_service/session/create/sdk.config.js
tests/idv_service/session/create/sdk.config.builder.test.js
types/src/idv_service/session/create/sdk.config.builder.d.ts
types/src/idv_service/session/create/sdk.config.d.ts

Update idv_service to expose a `withBrandId` in the SDK config builder.

SDK-2470 add brand_id to IDV SDK config

---

src/client/idv.client.js
src/idv_service/idv.service.js
src/idv_service/session/retrieve/devices/device.description.response.js
src/idv_service/session/retrieve/devices/session.tracked.devices.response.js
src/idv_service/session/retrieve/devices/tracked.device.event.response.js
tests/client/idv.client.spec.js
tests/idv_service/idv.service.spec.js
tests/idv_service/session/retrieve/devices/device.description.response.spec.js
tests/idv_service/session/retrieve/devices/tracked.device.event.response.spec.js
tests/idv_service/session/retrieve/devices/tracked.devices.response.spec.js
types/src/client/idv.client.d.ts
types/src/idv_service/idv.service.d.ts
types/src/idv_service/session/retrieve/devices/device.description.response.d.ts
types/src/idv_service/session/retrieve/devices/session.tracked.devices.response.d.ts
types/src/idv_service/session/retrieve/devices/tracked.device.event.response.d.ts

In IDV - client and service, added:
- `getSessionTrackedDevices()` to retrieve the devices (includes responses)
- `deleteSessionTrackedDevices()` to delete the devices

SDK-2477 IDV Session retrieve and delete device metadata

---

src/digital_identity_service/policy/wanted.attribute.builder.js
src/digital_identity_service/policy/wanted.attribute.js
tests/digital_identity_service/policy/wanted.attribute.builder.spec.js
types/src/digital_identity_service/policy/wanted.attribute.builder.d.ts
types/src/digital_identity_service/policy/wanted.attribute.d.ts

Added in `digital_identity_service` the wanted attribute extra options (`alternative name`, `optional`)

SDK-2359 Digital Identity - support wanted attributes extra options

---

src/dynamic_sharing_service/policy/wanted.attribute.builder.js
src/dynamic_sharing_service/policy/wanted.attribute.js
tests/dynamic_sharing_service/policy/wanted.attribute.builder.spec.js
types/src/dynamic_sharing_service/policy/wanted.attribute.builder.d.ts
types/src/dynamic_sharing_service/policy/wanted.attribute.d.ts

Can now set for **dynamic_sharing_service** policy with attributes that have alternative names, or that are optional:
```ts
const wantedAttribute = new WantedAttributeBuilder()
.withName("common_name")
.withAlternativeName("alt-name-1")
.build()
```
or
```ts
const wantedAttribute = new WantedAttributeBuilder()
.withName("common_name")
.withAlternativeNames(["alt-name-1", "alt-name-2"])
.build()
```
and
```ts
const wantedAttribute = new WantedAttributeBuilder()
.withName("some_attribute_name")
.withOptional(true)
.build()
```

SDK-2587 Add "optional" and "alternative_names" for share v1

---

src/data_type/age.verification.js
tests/data_type/age.verification.spec.js
types/src/data_type/age.verification.d.ts

Updated the data_type `AgeVerification` to handle the name parsing so it accepts an optional additional value (an age buffer - literally).

SDK-2588 Extend parsing of age verification attribute name
